update experiments

diff --git a/TLS/localhost/source/Dockerfile b/TLS/localhost/source/Dockerfile
--- a/TLS/localhost/source/Dockerfile
+++ b/TLS/localhost/source/Dockerfile
@@ -26,11 +26,11 @@ ARG CURL_VERSION="8.11.1"
 ARG OPENSSL_SOURCE="rtjk"
 ARG OPENSSL_TAG="fix_apps_verification"
 ###################################################
-ARG LIBOQS_SOURCE="rtjk"
-ARG LIBOQS_TAG="tlsexp-cross-2.2"
+ARG LIBOQS_SOURCE="open-quantum-safe"
+ARG LIBOQS_TAG="main"
 ###################################################
-ARG PROVIDER_SOURCE="rtjk"
-ARG PROVIDER_TAG="tlsexp-enable-all"
+ARG PROVIDER_SOURCE="open-quantum-safe"
+ARG PROVIDER_TAG="main"
 ###################################################
 
 # KEMs
@@ -42,7 +42,7 @@ ARG LIBOQS_BUILD_DEFINES="-DOQS_DIST_BUILD=ON"
 # get system packages
 RUN apk update && apk upgrade
 RUN apk add build-base linux-headers libtool automake autoconf cmake ninja make openssl openssl-dev git wget
-RUN apk add iproute2 net-tools iperf3 tcpdump
+RUN apk add iproute2 net-tools iperf3 tcpdump python3 py3-pip
 
 # get sources
 WORKDIR /opt
@@ -57,6 +57,10 @@ RUN mkdir build && \
     cd build && cmake -G"Ninja" .. ${LIBOQS_BUILD_DEFINES} -DCMAKE_INSTALL_PREFIX=/opt/oqssa && \
     ninja install
 
+# increase the limit for the certifcate chain size in OpenSSL
+WORKDIR /opt/openssl
+RUN sed -i 's/# define SSL_MAX_CERT_LIST_DEFAULT (1024\*100)/# define SSL_MAX_CERT_LIST_DEFAULT (1024*16000)/' include/openssl/ssl.h.in
+
 # install OpenSSL
 WORKDIR /opt/openssl
 RUN if [ -d "/opt/oqssa/lib64" ]; then ln -s "/opt/oqssa/lib64" "/opt/oqssa/lib"; fi && \
@@ -66,7 +70,15 @@ RUN LDFLAGS="-Wl,-rpath -Wl,/opt/oqssa/lib64" ./config shared --prefix=/opt/oqss
     make install_sw install_ssldirs;
 ENV PATH="/opt/oqssa/bin:${PATH}"
 
-# install provider
+# enable all signature schemes in oqs-provider
+WORKDIR /opt/oqs-provider
+COPY generate.yml oqs-template/generate.yml
+ENV LIBOQS_SRC_DIR=/opt/liboqs
+ENV LIBOQS_DOCS_DIR=/opt/liboqs/doc
+RUN pip3 install --break-system-packages -r oqs-template/requirements.txt
+RUN python3 oqs-template/generate.py
+
+# install oqs-provider
 WORKDIR /opt/oqs-provider
 RUN ln -s ../openssl . && \
     cmake -DOPENSSL_ROOT_DIR=/opt/oqssa -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=/opt/oqssa -S . -B _build && \
@@ -89,6 +101,13 @@ RUN env LDFLAGS=-Wl,-R/opt/oqssa/lib64  \
                     --with-ssl=/opt/oqssa && \
     make -j && \
     make install
+
+# log the software versions used
+WORKDIR /export
+RUN \
+    echo "$(git -C /opt/liboqs rev-parse --short HEAD) ${LIBOQS_SOURCE}/liboqs~${LIBOQS_TAG}"                 >  sw.txt && \
+    echo "$(git -C /opt/openssl rev-parse --short HEAD) ${OPENSSL_SOURCE}/openssl~${OPENSSL_TAG}"             >> sw.txt && \
+    echo "$(git -C /opt/oqs-provider rev-parse --short HEAD) ${PROVIDER_SOURCE}/oqs-provider~${PROVIDER_TAG}" >> sw.txt
 
 ################
 # SECOND STAGE #
@@ -123,15 +142,16 @@ WORKDIR /opt/test
 # root CA: generate key and certificate
 RUN openssl req -x509 -new -newkey ${SIG_ALG} -keyout root.key -out root.crt -nodes -subj "/CN=oqstest-root" -days 365 -config ${OPENSSL_CNF}
 
-# download LetsEncrypt root certificate
+# download LetsEncrypt root certificates
 RUN wget https://letsencrypt.org/certs/isrgrootx1.pem
 
-# boundle the 2 root certificates
+# boundle the root certificates
 RUN cat isrgrootx1.pem root.crt >> truststore.pem 
 
 # intermediate CA: generate key, CSR, and certificate
 RUN openssl req -new -newkey ${SIG_ALG} -keyout intermediate.key -out intermediate.csr -nodes -subj "/CN=oqstest-intermediate" -config ${OPENSSL_CNF}
 RUN echo "basicConstraints = CA:TRUE" > intermediate.cnf
+# RUN echo "1.2.3.4.5.6.7.8.1 = ASN1:UTF8String:$(awk -v n=9999 'BEGIN{for(i=0;i<n;i++)printf "A"}')" >> intermediate.cnf # inflate the certificate size
 RUN openssl x509 -req -in intermediate.csr -out intermediate.crt -CA root.crt -CAkey root.key -CAcreateserial -days 365 -extfile intermediate.cnf
 
 # server CA: generate key, CSR, and certificate
@@ -150,10 +170,22 @@ ENTRYPOINT \
     (openssl s_server -cert server.crt -cert_chain intermediate.crt -key server.key -groups ${KEM} -www -tls1_3 -accept localhost:4433 &) && \
     # wait for the server to respond
     while ! echo | openssl s_client -connect :4433 -CAfile truststore.pem -verify_return_error > /dev/null 2>&1 ; do sleep 0.1; done  && \
+    \
+    # start packet capture
+    # (tcpdump -i lo -w /export/traffic.pcap &) > /dev/null 2>&1 && \
+    # sleep 2 && \
+    # TCPDUMP_PID=$(pgrep tcpdump) && \
+    \
     # measure the number of connections in a given time frame
     # -new          use a new session for each connection (opposite of -reuse)
     # -verify x     verify that the certificate chain has at most x intermediate CAs
     openssl s_time -connect :4433 -CAfile truststore.pem -new -verify 1 -verify_return_error -time ${TEST_TIME} && \
+    # echo | openssl s_client -verify_return_error -connect localhost:4433 -CAfile root.crt -verify_depth 1 -keylogfile /export/sslkeys.log > /dev/null 2>&1 && echo "[OK]" || echo "[ERROR]" && \
+    \
+    # stop packet capture
+    # sleep 2 && \
+    # kill $TCPDUMP_PID && \
+    # sleep 2 && \
     \
     echo ">>>> done"
 
